/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Inventario;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import objetosNegocio.Modelo;
import objetosNegocio.Talla;

/**
 *
 * @author ZmSky
 */
public class FrameValidarInventario extends javax.swing.JFrame {

    private String accion = "default";

    /**
     * Creates new form FrameValidarInventario
     */
    public FrameValidarInventario(List<PanelModelo> paneles) {
        initComponents();

        setLocationRelativeTo(null);
        setVisible(true);
        construirTabla(paneles);
    }

    public void construirTabla(List<PanelModelo> listaPanelTest) {
        /**
         * Como un PanelInventariar puede contener 1 o mas PanelText, usamos un
         * for para obtener la informacion de cada uno de los PanelTest
         */
        for (int i = 0; i < listaPanelTest.size(); i++) {
            PanelModelo panelTest = listaPanelTest.get(i);
            Modelo modelo = new Modelo();

            /**
             * Esto sirve para verificar que los campos no esten vacios. En dado
             * caso de que si esten, no se conectara a la base de datos hasta
             * que se encuentre un modelo que si tenga los datos completos.
             */
            if (!panelTest.getModelo().isEmpty() && !String.valueOf(panelTest.getPrecio()).isEmpty()) {
                modelo.setNombre(panelTest.getModelo());
                modelo.setPrecio(panelTest.getPrecio());

                List<String> listaCantidades = new ArrayList();
                List<String> listaTallas = new ArrayList();
                
                for(PanelTalla panel : panelTest.getPanelesTalla()){
                    listaTallas.add(panel.getTalla());
                    listaCantidades.add(panel.getCantidad());
                }
                

                /**
                 * Igual aqui tenemos que checar que las cantidades de talla y
                 * producto no esten vacios.
                 */
                if (!listaCantidades.isEmpty() && !listaTallas.isEmpty()) {
                    PanelDetalleModelo panel = new PanelDetalleModelo(modelo, listaTallas, listaCantidades);
                        
                    panelDatos.add(panel);
                    panelDatos.revalidate();
                    panelDatos.repaint();
                } else {
                    JOptionPane.showMessageDialog(null, "Indique la cantidad de talla y producto");
                    accion = "Regresar";
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "El nombre y precio del modelo no puede estar vacio.");
                accion = "Regresar";
                dispose();
            }
        }
    }
    
    public String getAccion() {
        return accion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonCancelar = new javax.swing.JButton();
        botonTerminar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDatos.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(panelDatos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Los siguientes productos estan apunto de ser ingresados al sistema.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Si los datos son correctos, de click en terminar.");

        jLabel3.setText("Agregar Inventario");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonTerminar.setText("Terminar");
        botonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarActionPerformed(evt);
            }
        });

        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonTerminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonTerminar)
                    .addComponent(botonRegresar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarActionPerformed
        accion = "Terminar";
        dispose();
    }//GEN-LAST:event_botonTerminarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        accion = "Cancelar";
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        accion = "Regresar";
        dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonTerminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelDatos;
    // End of variables declaration//GEN-END:variables
}
