/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Inventario;

import java.awt.TextField;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JTextField;

/**
 *
 * @author ZmSky
 *
 * Esta clase crea metodos del tipo PanelTalla, estos paneles se encuentran
 * dentro de los componentes de tipo PanelTest.
 */
public class PanelTalla extends javax.swing.JPanel {

    /**
     * Creates new form PanelTalla
     */
    public PanelTalla() {
        initComponents();
    }

    public String getTalla(){
        return campoTextoTalla.getText();
    }
    
    public String getCantidad(){
        return campoTextoCantidad.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoTextoCantidad = new javax.swing.JTextField();
        campoTextoTalla = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setText("Talla");

        jLabel2.setText("Cantidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1))
            .addComponent(campoTextoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(campoTextoTalla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este metodo te regresa una lista con todas las tallas de un componente de
     * tipo PanelTalla.
     *
     * @return List<String>
     */
    public List<String> getListaTallasTexto() {
        listaTallasTexto = getListaTexto(this.listaTallas);
        return this.listaTallasTexto;
    }

    /**
     * Este metodo te regresa una lista con todas las cantides de tallas de un
     * componente de tipo PanelTalla
     *
     * @return
     */
    public List<String> getListaCantidadesTexto() {
        listaCantidadesTexto = getListaTexto(this.listaCantidades);
        return this.listaCantidadesTexto;
    }

    /**
     * Este metodo recibe una List<TextField> y regresa una lista de String con
     * los textos de los TextField
     *
     * @param lista
     * @return List<String>
     */
    private List<String> getListaTexto(List<TextField> lista) {
        List<String> listaTexto = new ArrayList<>();
        for (int i = 0; i < lista.size(); i++) {
            listaTexto.add(lista.get(i).getText());
        }
        return listaTexto;
    }

    /**
     * ATRIBUTOS DE LA CLASE
     * 
     * 
     * 
     * 
     * 
     */
    private List<String> listaTallasTexto = new ArrayList<>();
    private List<String> listaCantidadesTexto = new ArrayList<>();
    private List<TextField> listaTallas = new ArrayList<>();
    private List<TextField> listaCantidades = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoTextoCantidad;
    private javax.swing.JTextField campoTextoTalla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
