/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Inventario;

import java.awt.TextField;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JTextField;

/**
 *
 * @author ZmSky
 *
 * Esta clase crea metodos del tipo PanelTalla, estos paneles se encuentran
 * dentro de los componentes de tipo PanelTest.
 */
public class PanelTalla extends javax.swing.JPanel {

    /**
     * Creates new form PanelTalla
     */
    public PanelTalla() {
        initComponents();
        panelCosas.revalidate();
        panelCosas.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        panelCosas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
        agregarColumna = new javax.swing.JButton();

        jLabel1.setText("Talla");

        jLabel2.setText("Cantidad");

        jScrollPane1.setMinimumSize(new java.awt.Dimension(161, 150));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(161, 150));

        panelCosas.setLayout(new javax.swing.BoxLayout(panelCosas, javax.swing.BoxLayout.LINE_AXIS));
        panelCosas.add(jPanel1);
        panelCosas.add(jPanel2);

        jScrollPane1.setViewportView(panelCosas);

        agregarColumna.setText("+");
        agregarColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarColumnaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agregarColumna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarColumna)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este metodo entra en accion cuando se da click al boton "+", este se
     * encarga de agregar una columna mas de textFields al componente
     * PanelPantalla
     *
     * @param evt
     */
    private void agregarColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarColumnaActionPerformed
        TextField a = new TextField();
        TextField b = new TextField();

        a.setSize(40, 20);
        b.setSize(40, 20);

        listaTallas.add(a);
        listaCantidades.add(b);

        jPanel1.add(a);
        jPanel2.add(b);

        getRootPane().revalidate();
        getRootPane().repaint();
    }//GEN-LAST:event_agregarColumnaActionPerformed

    /**
     * Este metodo te regresa una lista con todas las tallas de un componente de
     * tipo PanelTalla.
     *
     * @return List<String>
     */
    public List<String> getListaTallasTexto() {
        listaTallasTexto = getListaTexto(this.listaTallas);
        return this.listaTallasTexto;
    }

    /**
     * Este metodo te regresa una lista con todas las cantides de tallas de un
     * componente de tipo PanelTalla
     *
     * @return
     */
    public List<String> getListaCantidadesTexto() {
        listaCantidadesTexto = getListaTexto(this.listaCantidades);
        return this.listaCantidadesTexto;
    }

    /**
     * Este metodo recibe una List<TextField> y regresa una lista de String con
     * los textos de los TextField
     *
     * @param lista
     * @return List<String>
     */
    private List<String> getListaTexto(List<TextField> lista) {
        List<String> listaTexto = new ArrayList<>();
        for (int i = 0; i < lista.size(); i++) {
            listaTexto.add(lista.get(i).getText());
        }
        return listaTexto;
    }

    /**
     * ATRIBUTOS DE LA CLASE
     * 
     * 
     * 
     * 
     * 
     */
    private List<String> listaTallasTexto = new ArrayList<>();
    private List<String> listaCantidadesTexto = new ArrayList<>();
    private List<TextField> listaTallas = new ArrayList<>();
    private List<TextField> listaCantidades = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarColumna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelCosas;
    // End of variables declaration//GEN-END:variables
}
