/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Inventario;

import javax.swing.JTextField;

/**
 *
 * @author ZmSky

 Los componentes del tipo "PanelModelo" tienen componentes del tipo "PanelTalla"
 dentro del mismo. Estos componentes se utilizan al momento de querer agregar
 al inventario Productos Nuevos o Registrados.
 */
public class PanelModelo extends javax.swing.JPanel {

    /**
     * Creates new form PanelTest
     */
    public PanelModelo() {
        initComponents();

        PanelTalla panel = new PanelTalla();
        add(panel);

        revalidate();
        repaint();
    }


    /**
     * Regresa el texto de FieldModelo
     * @return String
     */
    public String getModelo() {
        return this.textFieldModelo.getText();
    }

    /**
     * Regresa el componente de tipo "PanelTalla"
     * @return PanelTalla
     */
    public PanelTalla getPanelTalla() {
        return this.panelTalla;
    }

    /**
     * Regresa el precio del modelo.
     * @return float
     */
    public float getPrecio() {
        return new Float(textFieldPrecio.getText());
    }

    /**
     * Ingresa el texto del parametro al textFieldModelo
     * @param modelo 
     */
    public void setTextFieldModelo(String modelo) {
        this.textFieldModelo.setText(modelo);
    }

    /**
     * Ingresa el texto del parametro al textFieldPrecio
     * @param precio 
     */
    public void setTextFieldPrecio(String precio) {
        this.textFieldPrecio.setText(precio);
    }

    public JTextField getTextFieldModelo() {
        return textFieldModelo;
    }

    public JTextField getTextFieldPrecio() {
        return textFieldPrecio;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldModelo = new javax.swing.JTextField();
        panelTalla = new GUI.Inventario.PanelTalla();
        jLabel1 = new javax.swing.JLabel();
        textFieldPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setMinimumSize(new java.awt.Dimension(711, 96));

        textFieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldModeloActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Precio Unitario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(textFieldPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(textFieldModelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(panelTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldModeloActionPerformed


    /**
     * ATRIBUTOS DE LA CLASE
     * 
     * 
     * 
     * 
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private GUI.Inventario.PanelTalla panelTalla;
    private javax.swing.JTextField textFieldModelo;
    private javax.swing.JTextField textFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
