/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Inventario;

import java.util.List;
import java.util.Map;
import javax.swing.JLabel;
import objetosNegocio.Modelo;
import objetosNegocio.Talla;

/**
 *
 * @author ZmSky
 */
public class PanelDetalleModelo extends javax.swing.JPanel {

    /**
     * Creates new form PanelDetalleModelo
     */
    public PanelDetalleModelo(Modelo modelo, List<String> tallas, List<String> cantidades) {
        initComponents();
        
        llenarDatos(modelo, tallas, cantidades);
    }

    /**
     * Llena la tabla de datos con las tallas dadas por el parametro.
     * 
     * @param tallas 
     */
    private void llenarDatos(Modelo modelo, List<String> tallas, List<String> cantidades){
        labelModelo.setText(modelo.getNombre());
        labelPrecio.setText(String.valueOf(modelo.getPrecio()));
        
        int total = 0;
        
        for(int i = 0; i < tallas.size(); i++){
            String talla = tallas.get(i);
            int cantidad = Integer.parseInt(cantidades.get(i));
            JLabel label = new JLabel();
            
            label.setText("Talla " + talla + " / Cantidad: " + cantidad);
            
            panelDatos.add(label);
            panelDatos.revalidate();
            panelDatos.repaint();
            
            total+=cantidad;
        }
        
        labelCantidad.setText(String.valueOf(total));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelModelo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        scrollPane1 = new javax.swing.JScrollPane();
        panelDatos = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jlabel444 = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Modelo: ");

        labelModelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelModelo.setText("..");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Precio: ");

        labelPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPrecio.setText("..");

        scrollPane1.setBorder(null);

        panelDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDatos.setLayout(new java.awt.GridLayout(0, 1));
        scrollPane1.setViewportView(panelDatos);

        jlabel444.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel444.setText("Cantidad Total:");

        labelCantidad.setText("..");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabel444)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCantidad)
                            .addComponent(labelPrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelModelo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(69, Short.MAX_VALUE)
                        .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(labelModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelPrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel444)
                            .addComponent(labelCantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlabel444;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
