/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Inventario;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;

/**
 *
 * @author Roberto Pedraza
 */
public class PanelDetalladoInventariar extends javax.swing.JPanel {

    /**
     * Creates new form panelDetalladoInventariar
     */
    public PanelDetalladoInventariar() {
        initComponents();
        listaTallas.add(textFieldTalla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        botonAgregarTalla1 = new javax.swing.JButton();
        textFieldModelo1 = new javax.swing.JTextField();
        panelCantidad1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelTalla1 = new javax.swing.JPanel();
        textFieldCantidad1 = new javax.swing.JTextField();
        textFieldTalla1 = new javax.swing.JTextField();
        botonAgregarTalla = new javax.swing.JButton();
        textFieldModelo = new javax.swing.JTextField();
        panelCantidad = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelTalla = new javax.swing.JPanel();
        textFieldTalla = new javax.swing.JTextField();
        textFieldCantidad = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setPreferredSize(new java.awt.Dimension(693, 200));

        botonAgregarTalla1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonAgregarTalla1.setText("+");
        botonAgregarTalla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarTalla1ActionPerformed(evt);
            }
        });

        textFieldModelo1.setText("Modelo");

        javax.swing.GroupLayout panelCantidad1Layout = new javax.swing.GroupLayout(panelCantidad1);
        panelCantidad1.setLayout(panelCantidad1Layout);
        panelCantidad1Layout.setHorizontalGroup(
            panelCantidad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelCantidad1Layout.setVerticalGroup(
            panelCantidad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        panelTalla1.setPreferredSize(new java.awt.Dimension(20, 20));
        panelTalla1.setLayout(new java.awt.GridLayout(1, 1, 10, 10));
        jScrollPane3.setViewportView(panelTalla1);

        textFieldCantidad1.setText("Cantidad");

        textFieldTalla1.setText("Talla");
        textFieldTalla1.setPreferredSize(new java.awt.Dimension(10, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(textFieldModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(panelCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldTalla1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAgregarTalla1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTalla1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAgregarTalla1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(textFieldCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(panelCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        setPreferredSize(new java.awt.Dimension(693, 200));

        botonAgregarTalla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonAgregarTalla.setText("+");
        botonAgregarTalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarTallaActionPerformed(evt);
            }
        });

        textFieldModelo.setText("Modelo");

        javax.swing.GroupLayout panelCantidadLayout = new javax.swing.GroupLayout(panelCantidad);
        panelCantidad.setLayout(panelCantidadLayout);
        panelCantidadLayout.setHorizontalGroup(
            panelCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelCantidadLayout.setVerticalGroup(
            panelCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        panelTalla.setPreferredSize(new java.awt.Dimension(20, 20));
        panelTalla.setLayout(new java.awt.GridLayout(0, 1));

        textFieldTalla.setText("Talla");
        textFieldTalla.setMinimumSize(new java.awt.Dimension(10, 20));
        textFieldTalla.setPreferredSize(new java.awt.Dimension(10, 20));
        panelTalla.add(textFieldTalla);

        jScrollPane1.setViewportView(panelTalla);

        textFieldCantidad.setText("Cantidad");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(textFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregarTalla)
                    .addComponent(panelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173)
                        .addComponent(textFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(textFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(textFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAgregarTalla)
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(panelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarTallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarTallaActionPerformed
        JTextField textField = new JTextField();
        listaTallas.add(textField);
        textField.setSize(textFieldTalla.getSize());
        panelTalla.add(textField);
        panelTalla.revalidate();
        panelTalla.updateUI();
    }//GEN-LAST:event_botonAgregarTallaActionPerformed

    private void botonAgregarTalla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarTalla1ActionPerformed
        JTextField textField = new JTextField();
        listaTallas.add(textField);
        textField.setSize(textFieldTalla.getSize());
        panelTalla.add(textField);
        panelTalla.revalidate();
        panelTalla.updateUI();
    }//GEN-LAST:event_botonAgregarTalla1ActionPerformed

    private List<JTextField> listaTallas = new ArrayList<>();
    private List<JTextField> listaCantidades = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarTalla;
    private javax.swing.JButton botonAgregarTalla1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelCantidad;
    private javax.swing.JPanel panelCantidad1;
    private javax.swing.JPanel panelTalla;
    private javax.swing.JPanel panelTalla1;
    private javax.swing.JTextField textFieldCantidad;
    private javax.swing.JTextField textFieldCantidad1;
    private javax.swing.JTextField textFieldModelo;
    private javax.swing.JTextField textFieldModelo1;
    private javax.swing.JTextField textFieldTalla;
    private javax.swing.JTextField textFieldTalla1;
    // End of variables declaration//GEN-END:variables
}
